# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Fundamental_tutorial' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Fundamental_tutorial
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'Alamofire', '~> 5.5'
end

